apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-forslagsmotor-tilbehoer
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  liveness:
    path: /isalive
  readiness:
    path: /isready-composed
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  prometheus:
    enabled: true  # default: false. Pod will now be scraped for metrics by Prometheus.
    path: /metrics # Path where prometheus metrics are served.
  accessPolicy:
    inbound:
      rules:
        - application: hm-soknad
          namespace: teamdigihot
          cluster: prod-gcp
        - application: hm-forslagsmotor-tilbehoer-frontend
          namespace: teamdigihot
          cluster: prod-gcp
    outbound:
      rules:
        - application: hm-soknadsbehandling-db
        - application: hm-grunndata-api
      external:
        - host: hm-oebs-api-proxy.prod-fss-pub.nais.io
  envFrom:
    - secret: hm-influxdb-secret
  gcp:
    sqlInstances:
      - name: hm-forslagsmotor-tilbehoer-db-prod
        type: POSTGRES_12
        tier: db-g1-small
        diskType: SSD
        highAvailability: true
        diskSize: 10
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: hm-forslagsmotor-tilbehoer
            envVarPrefix: DB
        cascadingDelete: false
