apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-forslagsmotor-tilbehoer
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  prometheus:
    enabled: true  # default: false. Pod will now be scraped for metrics by Prometheus.
    path: /metrics # Path where prometheus metrics are served.
#  envFrom:
#    - secret: srvhm-dittnav-secret
#      # secret will be made available as environment variables