apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-forslagsmotor-tilbehoer
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  prometheus:
    enabled: true  # default: false. Pod will now be scraped for metrics by Prometheus.
    path: /metrics # Path where prometheus metrics are served.
  accessPolicy:
    inbound:
      rules:
        - application: hm-soknad
          namespace: teamdigihot
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-soknadsbehandling-db
  envFrom:
    - secret: hm-influxdb-secret
