name: deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
jobs:
  build:
    name: Bygg, deploy til dev-gcp og lag release
    permissions:
      packages: write
      contents: write
      id-token: write
    uses: navikt/hm-workflows/.github/workflows/deploy-dev.yaml@main
    with:
      manifest: .nais/nais-dev.yml
      java-version: 17
    secrets: inherit
