on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
    branches:
      - main
      - snyk-2022-02-07

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: monitor
          args: --configuration-attributes=usage:java-runtime --all-sub-projects --remote-repo-url=https://github.com/${{ github.repository }}.git --org=hjelpemiddelbehov