name: Vulnerabilities scanning of dependencies
on:
  schedule:
    - cron: '30 5 * * *' # jobben kjøres kl. 5:30 hverdag
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
      - Jenkinsfile
    branches:
      - *

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: monitor
          args: --configuration-attributes=usage:java-runtime --all-projects --remote-repo-url=https://github.com/${{ github.repository }}.git --org=hjelpemiddelbehov